# Codecov 配置
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  # 覆盖率精度（小数位数）
  precision: 2
  round: down
  range: "70...100"

  status:
    # 项目整体覆盖率门禁
    project:
      default:
        target: 90%      # 整体覆盖率目标 ≥90%
        threshold: 1%    # 允许波动 1%
        if_ci_failed: error

    # PR 增量覆盖率门禁
    patch:
      default:
        target: 95%      # 新代码覆盖率目标 ≥95%（核心业务标准）
        threshold: 1%

# 忽略的文件/目录
ignore:
  - "**/*_test.go"
  - "**/mock_*.go"
  - "**/mocks/**"
  - "**/example_*.go"
  - "**/doc.go"
  - "internal/e2e/**"
  - "examples/**"

# PR 评论配置
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true    # 仅在覆盖率变化时评论

# 标志配置（可按模块分别统计）
flags:
  unit:
    paths:
      - pkg/
      - internal/
    carryforward: true

  integration:
    paths:
      - pkg/
    carryforward: true
