// Code generated by MockGen. DO NOT EDIT.
// Source: etcd_interface.go
//
// Generated by this command:
//
//	mockgen -source=etcd_interface.go -destination=mock_etcd_test.go -package=xetcd
//

// Package xetcd is a generated GoMock package.
package xetcd

import (
	context "context"
	reflect "reflect"

	v3 "go.etcd.io/etcd/client/v3"
	gomock "go.uber.org/mock/gomock"
)

// MocketcdKV is a mock of etcdKV interface.
type MocketcdKV struct {
	ctrl     *gomock.Controller
	recorder *MocketcdKVMockRecorder
	isgomock struct{}
}

// MocketcdKVMockRecorder is the mock recorder for MocketcdKV.
type MocketcdKVMockRecorder struct {
	mock *MocketcdKV
}

// NewMocketcdKV creates a new mock instance.
func NewMocketcdKV(ctrl *gomock.Controller) *MocketcdKV {
	mock := &MocketcdKV{ctrl: ctrl}
	mock.recorder = &MocketcdKVMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocketcdKV) EXPECT() *MocketcdKVMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MocketcdKV) Delete(ctx context.Context, key string, opts ...v3.OpOption) (*v3.DeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*v3.DeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MocketcdKVMockRecorder) Delete(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocketcdKV)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MocketcdKV) Get(ctx context.Context, key string, opts ...v3.OpOption) (*v3.GetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*v3.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MocketcdKVMockRecorder) Get(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MocketcdKV)(nil).Get), varargs...)
}

// Put mocks base method.
func (m *MocketcdKV) Put(ctx context.Context, key, val string, opts ...v3.OpOption) (*v3.PutResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, val}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Put", varargs...)
	ret0, _ := ret[0].(*v3.PutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MocketcdKVMockRecorder) Put(ctx, key, val any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, val}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MocketcdKV)(nil).Put), varargs...)
}

// MocketcdLease is a mock of etcdLease interface.
type MocketcdLease struct {
	ctrl     *gomock.Controller
	recorder *MocketcdLeaseMockRecorder
	isgomock struct{}
}

// MocketcdLeaseMockRecorder is the mock recorder for MocketcdLease.
type MocketcdLeaseMockRecorder struct {
	mock *MocketcdLease
}

// NewMocketcdLease creates a new mock instance.
func NewMocketcdLease(ctrl *gomock.Controller) *MocketcdLease {
	mock := &MocketcdLease{ctrl: ctrl}
	mock.recorder = &MocketcdLeaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocketcdLease) EXPECT() *MocketcdLeaseMockRecorder {
	return m.recorder
}

// Grant mocks base method.
func (m *MocketcdLease) Grant(ctx context.Context, ttl int64) (*v3.LeaseGrantResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Grant", ctx, ttl)
	ret0, _ := ret[0].(*v3.LeaseGrantResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Grant indicates an expected call of Grant.
func (mr *MocketcdLeaseMockRecorder) Grant(ctx, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Grant", reflect.TypeOf((*MocketcdLease)(nil).Grant), ctx, ttl)
}

// Revoke mocks base method.
func (m *MocketcdLease) Revoke(ctx context.Context, id v3.LeaseID) (*v3.LeaseRevokeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id)
	ret0, _ := ret[0].(*v3.LeaseRevokeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MocketcdLeaseMockRecorder) Revoke(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MocketcdLease)(nil).Revoke), ctx, id)
}

// MocketcdWatcher is a mock of etcdWatcher interface.
type MocketcdWatcher struct {
	ctrl     *gomock.Controller
	recorder *MocketcdWatcherMockRecorder
	isgomock struct{}
}

// MocketcdWatcherMockRecorder is the mock recorder for MocketcdWatcher.
type MocketcdWatcherMockRecorder struct {
	mock *MocketcdWatcher
}

// NewMocketcdWatcher creates a new mock instance.
func NewMocketcdWatcher(ctrl *gomock.Controller) *MocketcdWatcher {
	mock := &MocketcdWatcher{ctrl: ctrl}
	mock.recorder = &MocketcdWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocketcdWatcher) EXPECT() *MocketcdWatcherMockRecorder {
	return m.recorder
}

// Watch mocks base method.
func (m *MocketcdWatcher) Watch(ctx context.Context, key string, opts ...v3.OpOption) v3.WatchChan {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Watch", varargs...)
	ret0, _ := ret[0].(v3.WatchChan)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MocketcdWatcherMockRecorder) Watch(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MocketcdWatcher)(nil).Watch), varargs...)
}

// MocketcdClient is a mock of etcdClient interface.
type MocketcdClient struct {
	ctrl     *gomock.Controller
	recorder *MocketcdClientMockRecorder
	isgomock struct{}
}

// MocketcdClientMockRecorder is the mock recorder for MocketcdClient.
type MocketcdClientMockRecorder struct {
	mock *MocketcdClient
}

// NewMocketcdClient creates a new mock instance.
func NewMocketcdClient(ctrl *gomock.Controller) *MocketcdClient {
	mock := &MocketcdClient{ctrl: ctrl}
	mock.recorder = &MocketcdClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocketcdClient) EXPECT() *MocketcdClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MocketcdClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MocketcdClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MocketcdClient)(nil).Close))
}

// Delete mocks base method.
func (m *MocketcdClient) Delete(ctx context.Context, key string, opts ...v3.OpOption) (*v3.DeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*v3.DeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MocketcdClientMockRecorder) Delete(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MocketcdClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MocketcdClient) Get(ctx context.Context, key string, opts ...v3.OpOption) (*v3.GetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*v3.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MocketcdClientMockRecorder) Get(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MocketcdClient)(nil).Get), varargs...)
}

// Grant mocks base method.
func (m *MocketcdClient) Grant(ctx context.Context, ttl int64) (*v3.LeaseGrantResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Grant", ctx, ttl)
	ret0, _ := ret[0].(*v3.LeaseGrantResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Grant indicates an expected call of Grant.
func (mr *MocketcdClientMockRecorder) Grant(ctx, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Grant", reflect.TypeOf((*MocketcdClient)(nil).Grant), ctx, ttl)
}

// Revoke mocks base method.
func (m *MocketcdClient) Revoke(ctx context.Context, id v3.LeaseID) (*v3.LeaseRevokeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id)
	ret0, _ := ret[0].(*v3.LeaseRevokeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MocketcdClientMockRecorder) Revoke(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MocketcdClient)(nil).Revoke), ctx, id)
}

// Put mocks base method.
func (m *MocketcdClient) Put(ctx context.Context, key, val string, opts ...v3.OpOption) (*v3.PutResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, val}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Put", varargs...)
	ret0, _ := ret[0].(*v3.PutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MocketcdClientMockRecorder) Put(ctx, key, val any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, val}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MocketcdClient)(nil).Put), varargs...)
}

// Watch mocks base method.
func (m *MocketcdClient) Watch(ctx context.Context, key string, opts ...v3.OpOption) v3.WatchChan {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Watch", varargs...)
	ret0, _ := ret[0].(v3.WatchChan)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MocketcdClientMockRecorder) Watch(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MocketcdClient)(nil).Watch), varargs...)
}
