// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/mq/xkafka/kafka_iface.go
//
// Generated by this command:
//
//	mockgen -source=pkg/mq/xkafka/kafka_iface.go -destination=pkg/mq/xkafka/mock_kafka_iface_test.go -package=xkafka
//

// Package xkafka is a generated GoMock package.
package xkafka

import (
	reflect "reflect"
	time "time"

	kafka "github.com/confluentinc/confluent-kafka-go/v2/kafka"
	gomock "go.uber.org/mock/gomock"
)

// MockkafkaProducerClient is a mock of kafkaProducerClient interface.
type MockkafkaProducerClient struct {
	ctrl     *gomock.Controller
	recorder *MockkafkaProducerClientMockRecorder
	isgomock struct{}
}

// MockkafkaProducerClientMockRecorder is the mock recorder for MockkafkaProducerClient.
type MockkafkaProducerClientMockRecorder struct {
	mock *MockkafkaProducerClient
}

// NewMockkafkaProducerClient creates a new mock instance.
func NewMockkafkaProducerClient(ctrl *gomock.Controller) *MockkafkaProducerClient {
	mock := &MockkafkaProducerClient{ctrl: ctrl}
	mock.recorder = &MockkafkaProducerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockkafkaProducerClient) EXPECT() *MockkafkaProducerClientMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockkafkaProducerClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockkafkaProducerClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockkafkaProducerClient)(nil).Close))
}

// Flush mocks base method.
func (m *MockkafkaProducerClient) Flush(timeoutMs int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", timeoutMs)
	ret0, _ := ret[0].(int)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockkafkaProducerClientMockRecorder) Flush(timeoutMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockkafkaProducerClient)(nil).Flush), timeoutMs)
}

// GetMetadata mocks base method.
func (m *MockkafkaProducerClient) GetMetadata(topic *string, allTopics bool, timeoutMs int) (*kafka.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", topic, allTopics, timeoutMs)
	ret0, _ := ret[0].(*kafka.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockkafkaProducerClientMockRecorder) GetMetadata(topic, allTopics, timeoutMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockkafkaProducerClient)(nil).GetMetadata), topic, allTopics, timeoutMs)
}

// Len mocks base method.
func (m *MockkafkaProducerClient) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockkafkaProducerClientMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockkafkaProducerClient)(nil).Len))
}

// Produce mocks base method.
func (m *MockkafkaProducerClient) Produce(msg *kafka.Message, deliveryChan chan kafka.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", msg, deliveryChan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockkafkaProducerClientMockRecorder) Produce(msg, deliveryChan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockkafkaProducerClient)(nil).Produce), msg, deliveryChan)
}

// MockkafkaConsumerClient is a mock of kafkaConsumerClient interface.
type MockkafkaConsumerClient struct {
	ctrl     *gomock.Controller
	recorder *MockkafkaConsumerClientMockRecorder
	isgomock struct{}
}

// MockkafkaConsumerClientMockRecorder is the mock recorder for MockkafkaConsumerClient.
type MockkafkaConsumerClientMockRecorder struct {
	mock *MockkafkaConsumerClient
}

// NewMockkafkaConsumerClient creates a new mock instance.
func NewMockkafkaConsumerClient(ctrl *gomock.Controller) *MockkafkaConsumerClient {
	mock := &MockkafkaConsumerClient{ctrl: ctrl}
	mock.recorder = &MockkafkaConsumerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockkafkaConsumerClient) EXPECT() *MockkafkaConsumerClientMockRecorder {
	return m.recorder
}

// Assignment mocks base method.
func (m *MockkafkaConsumerClient) Assignment() ([]kafka.TopicPartition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assignment")
	ret0, _ := ret[0].([]kafka.TopicPartition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assignment indicates an expected call of Assignment.
func (mr *MockkafkaConsumerClientMockRecorder) Assignment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assignment", reflect.TypeOf((*MockkafkaConsumerClient)(nil).Assignment))
}

// Close mocks base method.
func (m *MockkafkaConsumerClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockkafkaConsumerClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockkafkaConsumerClient)(nil).Close))
}

// Commit mocks base method.
func (m *MockkafkaConsumerClient) Commit() ([]kafka.TopicPartition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].([]kafka.TopicPartition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Commit indicates an expected call of Commit.
func (mr *MockkafkaConsumerClientMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockkafkaConsumerClient)(nil).Commit))
}

// Committed mocks base method.
func (m *MockkafkaConsumerClient) Committed(partitions []kafka.TopicPartition, timeoutMs int) ([]kafka.TopicPartition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Committed", partitions, timeoutMs)
	ret0, _ := ret[0].([]kafka.TopicPartition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Committed indicates an expected call of Committed.
func (mr *MockkafkaConsumerClientMockRecorder) Committed(partitions, timeoutMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Committed", reflect.TypeOf((*MockkafkaConsumerClient)(nil).Committed), partitions, timeoutMs)
}

// GetMetadata mocks base method.
func (m *MockkafkaConsumerClient) GetMetadata(topic *string, allTopics bool, timeoutMs int) (*kafka.Metadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", topic, allTopics, timeoutMs)
	ret0, _ := ret[0].(*kafka.Metadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockkafkaConsumerClientMockRecorder) GetMetadata(topic, allTopics, timeoutMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockkafkaConsumerClient)(nil).GetMetadata), topic, allTopics, timeoutMs)
}

// QueryWatermarkOffsets mocks base method.
func (m *MockkafkaConsumerClient) QueryWatermarkOffsets(topic string, partition int32, timeoutMs int) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryWatermarkOffsets", topic, partition, timeoutMs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryWatermarkOffsets indicates an expected call of QueryWatermarkOffsets.
func (mr *MockkafkaConsumerClientMockRecorder) QueryWatermarkOffsets(topic, partition, timeoutMs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryWatermarkOffsets", reflect.TypeOf((*MockkafkaConsumerClient)(nil).QueryWatermarkOffsets), topic, partition, timeoutMs)
}

// ReadMessage mocks base method.
func (m *MockkafkaConsumerClient) ReadMessage(timeout time.Duration) (*kafka.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadMessage", timeout)
	ret0, _ := ret[0].(*kafka.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadMessage indicates an expected call of ReadMessage.
func (mr *MockkafkaConsumerClientMockRecorder) ReadMessage(timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadMessage", reflect.TypeOf((*MockkafkaConsumerClient)(nil).ReadMessage), timeout)
}

// StoreMessage mocks base method.
func (m *MockkafkaConsumerClient) StoreMessage(msg *kafka.Message) ([]kafka.TopicPartition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreMessage", msg)
	ret0, _ := ret[0].([]kafka.TopicPartition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StoreMessage indicates an expected call of StoreMessage.
func (mr *MockkafkaConsumerClientMockRecorder) StoreMessage(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreMessage", reflect.TypeOf((*MockkafkaConsumerClient)(nil).StoreMessage), msg)
}
